version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mitch-bilensky-ca"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bzw1xzl756lj"
s3_prefix = "mitch-bilensky-ca"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
