# This is a basic workflow to help you get started with Actions

name: CI
env:
  NODE_VERSION: '16.x'   # set this to the node version to use

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: mitch.bilensky.ca
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: |
        cd site
        npm install
        npm run build --if-present
        cd ../
